version: '3'
services:
    apache:
        build: .docker/apache
        container_name: sf4_apache
        ports:
            - "8000:80"
        volumes:
            - .docker/config/vhosts:/etc/apache2/sites-enabled
            - .:/home/wwwroot/sf4
        depends_on:
            - php

    mysql:
        image: mysql
        container_name: sf4_mysql
        ports:
            - "3306"
        volumes:
            - .docker/data/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: sf4
            MYSQL_USER: sf4
            MYSQL_PASSWORD: sf4
        command: "--default-authentication-plugin=mysql_native_password"

    php:
        build: .docker/php
        container_name: sf4_php
        ports:
            - "9000"
        volumes:
            - .:/home/wwwroot/sf4
        environment:
            - maildev_host=sf4_maildev
        depends_on:
            - maildev
            - mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: sf4_phpmyadmin
        ports:
            - "8080:80"
        environment:
            PMA_HOST: mysql
            PMA_PORT: "3306"
        depends_on:
            - mysql

    maildev:
        image: djfarrelly/maildev
        container_name: sf4_maildev
        ports:
            - "8001:80"

    mercure:
        image: dunglas/mercure
        container_name: sf4_mercure
        ports:
            - "3000:3000"
        environment: 
            - JWT_KEY=${MERCURE_JWT_KEY}
            - ADDR=${MERCURE_SERVER_PORT}
            - PUBLISH_ALLOWED_ORIGINS=*
            - ALLOW_ANONYMOUS=1
            - CORS_ALLOWED_ORIGINS=*
